import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import FAQ from "@/components/FAQ";

const poppins = Poppins({
  weight: "200",
  subsets: ["latin"],
  style: ["normal"],
  display: "swap",
});

export const metadata = {
  title: "HideNothin",
  description: "Generated by create next app",
  icons: [{ rel: "icon", url: "/logo.svg" }],
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins} `}>
        <Navbar />
        {children}
        <FAQ />
        <Footer />
      </body>
    </html>
  );
}
